### ISSUE TITLE
Feature: YAML HTTP Action

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-tool_trigger#28]
A new action that allows the data sent and its schema to be defined using YAML.
This requirement is based on an internal discussion. 

The current placeholder format of: `{username}` is great for simple outputs or where the output is mostly unstructured. The email action is a good example of where placeholders work well.  Where placeholders don't work well is for complex JSON schema's and where there needs to be a more structured way of defining the output.  An example of what a YAML definition might look like is:
```
output: json
parameters:
  - name: other_username
    required: true # Fail if this field isn't pass to step.
    type: string
    default: "some  user"
  - name: eventname
    required: true
    type: string
    urlencode: true # \core\event\user_login_failed becomes %5Ccore%5Cevent%5Cuser_login_failed
```
In the above the name value `other_username` would be made the name of a name value pair and the corresponding value derived from the event would make up the value.  This approach would also allow us to explicitly check and handle required fields as well as default values.  Allowing us to fail and catch errors.  This would be useful as not all possible values for an event are passed every time the event is fired.

The new action should also support the PUT, POST and DELETE HTTP verbs.
It should also support sending the data in JSON and XML formats.
